type: object
properties:
  id:
    type: number
  name:
    type: string
  ingredientProduct:
    type: number
  unitProduct:
    type: number
  price:
    type: number
  store:
    type: string
  is_deleted:
    type: boolean
    default: false
  is_organic:
    type: boolean
    default: false
required:
  - ingredientProduct
  - unitProduct