swagger: '2.0'
info:
  title: Grocer API
  version: '0.0.4'
schemes:
  - http
produces:
  - application/json

paths:
  $fs-ref: ./endpoints/index.yaml

parameters:
  $fs-ref: ./globals/parameters.yaml

responses:
  $fs-ref: ./globals/responses.yaml

definitions:
  $fs-ref: ./definitions/index.yaml
